// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace StudentManagement.Entities
{
    public partial class StudentMangementDBContext : DbContext
    {
        public StudentMangementDBContext()
        {
        }

        public StudentMangementDBContext(DbContextOptions<StudentMangementDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<student_Detail_Table> student_Detail_Table { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Student_Mangement_Database;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<student_Detail_Table>(entity =>
            {
                entity.Property(e => e.Create_Time_Stamp).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Favorite_Subject).IsUnicode(false);

                entity.Property(e => e.First_Name).IsUnicode(false);

                entity.Property(e => e.Intersted_Course).IsUnicode(false);

                entity.Property(e => e.Last_Name).IsUnicode(false);

                entity.Property(e => e.Update_Time_stamp).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}